---
- name: Add all server entries to /etc/hosts
  ansible.builtin.lineinfile:
    path: /etc/hosts
    regexp: "^.*\\s+{{ item.name }}$"
    line: "{{ item.ip }} {{ item.name }}"
    state: present
  loop: "{{ all_server_entries }}"
  loop_control:
    label: "{{ item.name }}"
